---
title: "Reagan's Blog"
date: 2019-01-11
---
title: Reagan's Blog
author: Reagan Hoback
email: rlh002@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  This site is for my skills and certification course at the University of Tulsa.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
